// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (
    id,
    user_id,
    name,
    is_active
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, name, is_active, created_at, updated_at, deleted_at
`

type CreateCollectionParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   string    `json:"user_id"`
	Name     string    `json:"name"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.IsActive,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findCollectionByID = `-- name: FindCollectionByID :one
SELECT id, user_id, name, is_active, created_at, updated_at, deleted_at
FROM collections
WHERE id = $1 AND user_id = $2
`

type FindCollectionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) FindCollectionByID(ctx context.Context, arg FindCollectionByIDParams) (Collection, error) {
	row := q.db.QueryRow(ctx, findCollectionByID, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findLiveCollectionByName = `-- name: FindLiveCollectionByName :one
SELECT id, user_id, name, is_active, created_at, updated_at, deleted_at
FROM collections
WHERE user_id = $1 AND name = $2 AND deleted_at IS NULL
`

type FindLiveCollectionByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) FindLiveCollectionByName(ctx context.Context, arg FindLiveCollectionByNameParams) (Collection, error) {
	row := q.db.QueryRow(ctx, findLiveCollectionByName, arg.UserID, arg.Name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCollectionsUpdatedSince = `-- name: ListCollectionsUpdatedSince :many

SELECT id, user_id, name, is_active, created_at, updated_at, deleted_at
FROM collections
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
`

type ListCollectionsUpdatedSinceParams struct {
	UserID    string    `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Queries against the `collections` table.
// Same conventions as words.sql — see its comment block.
func (q *Queries) ListCollectionsUpdatedSince(ctx context.Context, arg ListCollectionsUpdatedSinceParams) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsUpdatedSince, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCollection = `-- name: SoftDeleteCollection :exec
UPDATE collections
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteCollectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

// Soft-delete a collection. The cascade to word_collections is handled
// separately (SoftDeleteLinksByCollection in word_collections.sql) in
// the same transaction from the handler, so both rows are visible to the
// next sync pull.
func (q *Queries) SoftDeleteCollection(ctx context.Context, arg SoftDeleteCollectionParams) error {
	_, err := q.db.Exec(ctx, softDeleteCollection, arg.ID, arg.UserID)
	return err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET
    name       = COALESCE($1::text,       name),
    is_active  = COALESCE($2::bool,  is_active),
    updated_at = now()
WHERE id = $3
  AND user_id = $4
  AND deleted_at IS NULL
RETURNING id, user_id, name, is_active, created_at, updated_at, deleted_at
`

type UpdateCollectionParams struct {
	Name     *string   `json:"name"`
	IsActive *bool     `json:"is_active"`
	ID       uuid.UUID `json:"id"`
	UserID   string    `json:"user_id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.Name,
		arg.IsActive,
		arg.ID,
		arg.UserID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
