// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Collection struct {
	ID        uuid.UUID  `json:"id"`
	UserID    string     `json:"user_id"`
	Name      string     `json:"name"`
	IsActive  bool       `json:"is_active"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Word struct {
	ID             uuid.UUID  `json:"id"`
	UserID         string     `json:"user_id"`
	OriginalWord   string     `json:"original_word"`
	NormalizedWord string     `json:"normalized_word"`
	Translation    string     `json:"translation"`
	ExampleUsage   string     `json:"example_usage"`
	Explanation    string     `json:"explanation"`
	Pronunciation  string     `json:"pronunciation"`
	AddedDate      time.Time  `json:"added_date"`
	LastShownDate  *time.Time `json:"last_shown_date"`
	ShowCount      int32      `json:"show_count"`
	Difficulty     int16      `json:"difficulty"`
	IsLearned      bool       `json:"is_learned"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
}

type WordCollection struct {
	ID           uuid.UUID  `json:"id"`
	UserID       string     `json:"user_id"`
	WordID       uuid.UUID  `json:"word_id"`
	CollectionID uuid.UUID  `json:"collection_id"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}
