// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: word_collections.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWordCollection = `-- name: CreateWordCollection :one
INSERT INTO word_collections (
    id,
    user_id,
    word_id,
    collection_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, word_id, collection_id, created_at, updated_at, deleted_at
`

type CreateWordCollectionParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       string    `json:"user_id"`
	WordID       uuid.UUID `json:"word_id"`
	CollectionID uuid.UUID `json:"collection_id"`
}

func (q *Queries) CreateWordCollection(ctx context.Context, arg CreateWordCollectionParams) (WordCollection, error) {
	row := q.db.QueryRow(ctx, createWordCollection,
		arg.ID,
		arg.UserID,
		arg.WordID,
		arg.CollectionID,
	)
	var i WordCollection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WordID,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findLiveWordCollection = `-- name: FindLiveWordCollection :one
SELECT id, user_id, word_id, collection_id, created_at, updated_at, deleted_at
FROM word_collections
WHERE user_id = $1
  AND word_id = $2
  AND collection_id = $3
  AND deleted_at IS NULL
`

type FindLiveWordCollectionParams struct {
	UserID       string    `json:"user_id"`
	WordID       uuid.UUID `json:"word_id"`
	CollectionID uuid.UUID `json:"collection_id"`
}

// 409 check for POST /v1/collections/{cid}/words/{wid}.
func (q *Queries) FindLiveWordCollection(ctx context.Context, arg FindLiveWordCollectionParams) (WordCollection, error) {
	row := q.db.QueryRow(ctx, findLiveWordCollection, arg.UserID, arg.WordID, arg.CollectionID)
	var i WordCollection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WordID,
		&i.CollectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWordCollectionsUpdatedSince = `-- name: ListWordCollectionsUpdatedSince :many

SELECT id, user_id, word_id, collection_id, created_at, updated_at, deleted_at
FROM word_collections
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
`

type ListWordCollectionsUpdatedSinceParams struct {
	UserID    string    `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Queries against the `word_collections` M2M join table.
//
// Each row has its own UUID PK so we can tombstone and re-create the
// same (word_id, collection_id) pair without the old row blocking the
// new one. The partial unique index `word_collections_pair_live` enforces
// that only one *live* link per pair can exist at a time.
func (q *Queries) ListWordCollectionsUpdatedSince(ctx context.Context, arg ListWordCollectionsUpdatedSinceParams) ([]WordCollection, error) {
	rows, err := q.db.Query(ctx, listWordCollectionsUpdatedSince, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WordCollection{}
	for rows.Next() {
		var i WordCollection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WordID,
			&i.CollectionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLinksByCollection = `-- name: SoftDeleteLinksByCollection :exec
UPDATE word_collections
SET deleted_at = now(),
    updated_at = now()
WHERE user_id = $1 AND collection_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLinksByCollectionParams struct {
	UserID       string    `json:"user_id"`
	CollectionID uuid.UUID `json:"collection_id"`
}

// Same pattern, from the DELETE /v1/collections/{id} handler.
func (q *Queries) SoftDeleteLinksByCollection(ctx context.Context, arg SoftDeleteLinksByCollectionParams) error {
	_, err := q.db.Exec(ctx, softDeleteLinksByCollection, arg.UserID, arg.CollectionID)
	return err
}

const softDeleteLinksByWord = `-- name: SoftDeleteLinksByWord :exec
UPDATE word_collections
SET deleted_at = now(),
    updated_at = now()
WHERE user_id = $1 AND word_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLinksByWordParams struct {
	UserID string    `json:"user_id"`
	WordID uuid.UUID `json:"word_id"`
}

// Called from the DELETE /v1/words/{id} handler in the same transaction
// as SoftDeleteWord. All live links pointing at a deleted word become
// tombstones with a bumped updated_at so other devices drop them.
func (q *Queries) SoftDeleteLinksByWord(ctx context.Context, arg SoftDeleteLinksByWordParams) error {
	_, err := q.db.Exec(ctx, softDeleteLinksByWord, arg.UserID, arg.WordID)
	return err
}

const softDeleteWordCollection = `-- name: SoftDeleteWordCollection :exec
UPDATE word_collections
SET deleted_at = now(),
    updated_at = now()
WHERE user_id = $1
  AND word_id = $2
  AND collection_id = $3
  AND deleted_at IS NULL
`

type SoftDeleteWordCollectionParams struct {
	UserID       string    `json:"user_id"`
	WordID       uuid.UUID `json:"word_id"`
	CollectionID uuid.UUID `json:"collection_id"`
}

// DELETE /v1/collections/{cid}/words/{wid}.
func (q *Queries) SoftDeleteWordCollection(ctx context.Context, arg SoftDeleteWordCollectionParams) error {
	_, err := q.db.Exec(ctx, softDeleteWordCollection, arg.UserID, arg.WordID, arg.CollectionID)
	return err
}
