// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: words.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWord = `-- name: CreateWord :one
INSERT INTO words (
    id,
    user_id,
    original_word,
    normalized_word,
    translation,
    example_usage,
    explanation,
    pronunciation,
    added_date,
    difficulty,
    is_learned
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, original_word, normalized_word, translation, example_usage, explanation, pronunciation, added_date, last_shown_date, show_count, difficulty, is_learned, created_at, updated_at, deleted_at
`

type CreateWordParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         string    `json:"user_id"`
	OriginalWord   string    `json:"original_word"`
	NormalizedWord string    `json:"normalized_word"`
	Translation    string    `json:"translation"`
	ExampleUsage   string    `json:"example_usage"`
	Explanation    string    `json:"explanation"`
	Pronunciation  string    `json:"pronunciation"`
	AddedDate      time.Time `json:"added_date"`
	Difficulty     int16     `json:"difficulty"`
	IsLearned      bool      `json:"is_learned"`
}

// INSERT with all fields explicit. The client may provide id (idempotent
// retry / migration path); handlers should generate one if missing.
// added_date defaults to now() if the client doesn't supply it.
func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (Word, error) {
	row := q.db.QueryRow(ctx, createWord,
		arg.ID,
		arg.UserID,
		arg.OriginalWord,
		arg.NormalizedWord,
		arg.Translation,
		arg.ExampleUsage,
		arg.Explanation,
		arg.Pronunciation,
		arg.AddedDate,
		arg.Difficulty,
		arg.IsLearned,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalWord,
		&i.NormalizedWord,
		&i.Translation,
		&i.ExampleUsage,
		&i.Explanation,
		&i.Pronunciation,
		&i.AddedDate,
		&i.LastShownDate,
		&i.ShowCount,
		&i.Difficulty,
		&i.IsLearned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findLiveWordByNormalized = `-- name: FindLiveWordByNormalized :one
SELECT id, user_id, original_word, normalized_word, translation, example_usage, explanation, pronunciation, added_date, last_shown_date, show_count, difficulty, is_learned, created_at, updated_at, deleted_at
FROM words
WHERE user_id = $1 AND normalized_word = $2 AND deleted_at IS NULL
`

type FindLiveWordByNormalizedParams struct {
	UserID         string `json:"user_id"`
	NormalizedWord string `json:"normalized_word"`
}

// 409 collision check for POST /v1/words. Returns the existing live row
// so the handler can include existing_id in the error body.
func (q *Queries) FindLiveWordByNormalized(ctx context.Context, arg FindLiveWordByNormalizedParams) (Word, error) {
	row := q.db.QueryRow(ctx, findLiveWordByNormalized, arg.UserID, arg.NormalizedWord)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalWord,
		&i.NormalizedWord,
		&i.Translation,
		&i.ExampleUsage,
		&i.Explanation,
		&i.Pronunciation,
		&i.AddedDate,
		&i.LastShownDate,
		&i.ShowCount,
		&i.Difficulty,
		&i.IsLearned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findWordByID = `-- name: FindWordByID :one
SELECT id, user_id, original_word, normalized_word, translation, example_usage, explanation, pronunciation, added_date, last_shown_date, show_count, difficulty, is_learned, created_at, updated_at, deleted_at
FROM words
WHERE id = $1 AND user_id = $2
`

type FindWordByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

// Used by PATCH/DELETE handlers for 404 checks. Includes tombstones so we
// can distinguish "not yours" from "already deleted" if we ever want to.
func (q *Queries) FindWordByID(ctx context.Context, arg FindWordByIDParams) (Word, error) {
	row := q.db.QueryRow(ctx, findWordByID, arg.ID, arg.UserID)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalWord,
		&i.NormalizedWord,
		&i.Translation,
		&i.ExampleUsage,
		&i.Explanation,
		&i.Pronunciation,
		&i.AddedDate,
		&i.LastShownDate,
		&i.ShowCount,
		&i.Difficulty,
		&i.IsLearned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWordsUpdatedSince = `-- name: ListWordsUpdatedSince :many

SELECT id, user_id, original_word, normalized_word, translation, example_usage, explanation, pronunciation, added_date, last_shown_date, show_count, difficulty, is_learned, created_at, updated_at, deleted_at
FROM words
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
`

type ListWordsUpdatedSinceParams struct {
	UserID    string    `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Queries against the `words` table.
//
// A few conventions used across this file:
//
//   - Every query that touches a user's data takes user_id as the first
//     parameter and filters on it. This is multi-tenant isolation at the
//     query layer — no row ever leaks between users, even if an upstream
//     handler bug forgets a check.
//
//   - `updated_at = now()` is set on every write so the sync pull cursor
//     sees the row on the next pull. We never pass updated_at from Go.
//
//   - "Live" means `deleted_at IS NULL`. Queries named *Live operate only
//     on non-tombstoned rows; plain queries (used by sync pull) return
//     tombstones too so clients can drop deleted rows from their cache.
//
//   - PATCH semantics use `COALESCE(sqlc.narg('x'), x)` — if the named
//     arg is NULL, keep the existing value; otherwise replace. This is
//     the idiomatic sqlc pattern for partial updates.
//
// Delta pull for /v1/sync/pull. Returns rows (including tombstones) that
// have been touched since the given timestamp. Ordering by updated_at
// makes the stream easy for the client to apply in order.
func (q *Queries) ListWordsUpdatedSince(ctx context.Context, arg ListWordsUpdatedSinceParams) ([]Word, error) {
	rows, err := q.db.Query(ctx, listWordsUpdatedSince, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Word{}
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalWord,
			&i.NormalizedWord,
			&i.Translation,
			&i.ExampleUsage,
			&i.Explanation,
			&i.Pronunciation,
			&i.AddedDate,
			&i.LastShownDate,
			&i.ShowCount,
			&i.Difficulty,
			&i.IsLearned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWord = `-- name: SoftDeleteWord :exec
UPDATE words
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteWordParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

// DELETE endpoint. Sets deleted_at (the tombstone) and bumps updated_at
// so the next pull propagates the delete to other devices.
func (q *Queries) SoftDeleteWord(ctx context.Context, arg SoftDeleteWordParams) error {
	_, err := q.db.Exec(ctx, softDeleteWord, arg.ID, arg.UserID)
	return err
}

const updateWord = `-- name: UpdateWord :one
UPDATE words
SET
    original_word  = COALESCE($1::text,        original_word),
    translation    = COALESCE($2::text,          translation),
    example_usage  = COALESCE($3::text,        example_usage),
    explanation    = COALESCE($4::text,          explanation),
    pronunciation  = COALESCE($5::text,        pronunciation),
    difficulty     = COALESCE($6::smallint,       difficulty),
    is_learned     = COALESCE($7::boolean,        is_learned),
    updated_at     = now()
WHERE id = $8
  AND user_id = $9
  AND deleted_at IS NULL
RETURNING id, user_id, original_word, normalized_word, translation, example_usage, explanation, pronunciation, added_date, last_shown_date, show_count, difficulty, is_learned, created_at, updated_at, deleted_at
`

type UpdateWordParams struct {
	OriginalWord  *string   `json:"original_word"`
	Translation   *string   `json:"translation"`
	ExampleUsage  *string   `json:"example_usage"`
	Explanation   *string   `json:"explanation"`
	Pronunciation *string   `json:"pronunciation"`
	Difficulty    *int16    `json:"difficulty"`
	IsLearned     *bool     `json:"is_learned"`
	ID            uuid.UUID `json:"id"`
	UserID        string    `json:"user_id"`
}

// PATCH endpoint. Null args mean "don't touch." updated_at is always
// bumped to now() because a PATCH is a mutation by definition.
func (q *Queries) UpdateWord(ctx context.Context, arg UpdateWordParams) (Word, error) {
	row := q.db.QueryRow(ctx, updateWord,
		arg.OriginalWord,
		arg.Translation,
		arg.ExampleUsage,
		arg.Explanation,
		arg.Pronunciation,
		arg.Difficulty,
		arg.IsLearned,
		arg.ID,
		arg.UserID,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalWord,
		&i.NormalizedWord,
		&i.Translation,
		&i.ExampleUsage,
		&i.Explanation,
		&i.Pronunciation,
		&i.AddedDate,
		&i.LastShownDate,
		&i.ShowCount,
		&i.Difficulty,
		&i.IsLearned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWordProgress = `-- name: UpdateWordProgress :exec
UPDATE words
SET show_count      = $1,
    last_shown_date = $2,
    is_learned      = $3,
    updated_at      = now()
WHERE id = $4
  AND user_id = $5
  AND deleted_at IS NULL
`

type UpdateWordProgressParams struct {
	ShowCount     int32      `json:"show_count"`
	LastShownDate *time.Time `json:"last_shown_date"`
	IsLearned     bool       `json:"is_learned"`
	ID            uuid.UUID  `json:"id"`
	UserID        string     `json:"user_id"`
}

// PATCH /v1/words/progress/batch, called once per id inside a single Go
// transaction. All three progress fields are always supplied — the client
// flushes a snapshot of its local state, not a delta.
func (q *Queries) UpdateWordProgress(ctx context.Context, arg UpdateWordProgressParams) error {
	_, err := q.db.Exec(ctx, updateWordProgress,
		arg.ShowCount,
		arg.LastShownDate,
		arg.IsLearned,
		arg.ID,
		arg.UserID,
	)
	return err
}
