package com.rsln.wordflow.data.remote

import com.rsln.wordflow.data.local.entity.CollectionEntity
import com.rsln.wordflow.data.local.entity.WordEntity

/**
 * DTO ↔ Entity conversions. Kept in a single file so adding a new
 * field on either side only requires one edit instead of hunting
 * through the repository.
 *
 * Local rows get a brand-new autoGenerated id=0 so Room assigns a
 * fresh local primary key. The server-side UUID is preserved in the
 * `remoteId` column for subsequent PATCH/DELETE routing.
 */

fun WordDto.toEntity(): WordEntity = WordEntity(
    id = 0,
    remoteId = id,
    originalWord = originalWord,
    normalizedWord = normalizedWord,
    translation = translation,
    exampleUsage = exampleUsage,
    explanation = explanation,
    pronunciation = pronunciation,
    addedDate = IsoDate.parseOrNow(addedDate),
    lastShownDate = IsoDate.parse(lastShownDate),
    showCount = showCount,
    difficulty = difficulty,
    isLearned = isLearned,
    updatedAt = IsoDate.parseOrNow(updatedAt),
    pendingProgressPush = false
)

fun CollectionDto.toEntity(): CollectionEntity = CollectionEntity(
    id = 0,
    remoteId = id,
    name = name,
    isActive = isActive,
    createdAt = IsoDate.parseOrNow(createdAt),
    updatedAt = IsoDate.parseOrNow(updatedAt)
)
